# Generated by Django 4.2.3 on 2023-07-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65)),
                ('sexo', models.CharField(max_length=9)),
                ('anime', models.CharField(max_length=65)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Malo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65)),
                ('sexo', models.CharField(max_length=9)),
                ('anime', models.CharField(max_length=65)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Neutral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65)),
                ('sexo', models.CharField(max_length=9)),
                ('anime', models.CharField(max_length=65)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65)),
                ('sexo', models.CharField(max_length=9)),
                ('anime', models.CharField(max_length=65)),
                ('bio', models.TextField()),
            ],
        ),
    ]
