# Generated by Django 4.2.3 on 2023-07-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bueno',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='malo',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='neutral',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='total',
            name='anime',
        ),
        migrations.AddField(
            model_name='total',
            name='naturaleza',
            field=models.CharField(default='Bueno', max_length=6),
            preserve_default=False,
        ),
    ]
