# Generated by Django 4.2.3 on 2023-07-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0002_remove_bueno_anime_remove_malo_anime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
    ]
